GET http://localhost:8000/api/v1/custom_forms/custom_form/
content-type: application/json

###

POST http://localhost:8000/api/v1/custom_forms/custom_form/
content-type: application/json

{
    "name":"test5",
    "source":"https://gncitizen.fr",
    "json_schema_form":{"key":"value"},
    "tags":[{"label":"harry"},{"label":"potter"}]
}