# Generated by Django 3.2.3 on 2022-02-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Label'),
        ),
    ]
