# Generated by Django 3.2.3 on 2022-02-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="nom")),
                ("json_schema_form", models.JSONField(verbose_name="json schema form")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date d'ajout")),
                ("source", models.URLField(verbose_name="Source")),
            ],
            options={
                "verbose_name": "Custom form",
                "verbose_name_plural": "Custom forms",
            },
        ),
    ]
