# Generated by Django 3.2.3 on 2022-02-02 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commons", "__first__"),
        ("custom_forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customform",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customform",
            name="tags",
            field=models.ManyToManyField(
                to="commons.Tags", verbose_name="Tags"
            ),
        ),
        migrations.AddField(
            model_name="customform",
            name="timestamp_create",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Create timestamp",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customform",
            name="timestamp_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Update timestamp"
            ),
        ),
        migrations.AddField(
            model_name="customform",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
