# Generated by Django 3.2.3 on 2022-02-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_forms", "0002_auto_20220202_2050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customform",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="nom"),
        ),
        migrations.AlterUniqueTogether(
            name="customform",
            unique_together={("name", "source")},
        ),
    ]
